### PR TITLE
Added some card styles  😃

### PR DESCRIPTION
**Pull request by ebadfd**
I have added some card styles and also added some box shadow around the box , also created a bit different button style check that out.

### CODE REVIEW

**Comment by ebadfd** [comment]
Here's some demo images

Screenshot from 2021-09-10 00-26-03

Screenshot from 2021-09-10 00-26-20

**Comment by ThamiduAnjana** [comment]
Hey! Dasith, I hope you add comments for all CSS commands. Please do it and again create pull request..

**Comment by ThamiduAnjana** [comment]
Its will helpful others

**Comment by ThamiduAnjana** [comment]
Hey! 👋  Dasith, I hope you add comments for all CSS commands. Please do it and again create pull request..
Its will helpful others

Thank You 💞 for Join With me.. 💯  😊

**Pull request merged**
